### ISSUE TITLE
Key used for `nodeAffinity` does not match with actual one

### ISSUE THREAD

**Issue by hoony9x-furiosa-ai** [furiosa-ai/furiosa-metrics-exporter#20]
## Describe the bug

https://github.com/furiosa-ai/furiosa-metrics-exporter/blob/49af33d393841e9762f6dbd6fc70c8019ba980df/deployments/helm/values.yaml#L16-L23
- key `feature.node.kubernetes.io/pci-1ed2.present` is expected, but actual value labeled in the node is `feature.node.kubernetes.io/pci-1200_1ed2.present`.

## Expected behavior

Must use correct key in `values.yaml`.

## Additional context

Below YAML represents the node `ms03-ceo-008`.

```yaml
apiVersion: v1
kind: Node
metadata:
  name: ms03-ceo-008
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/cpu-cpuid.ADX: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AESNI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AMXBF16: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AMXINT8: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AMXTILE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512BF16: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512BITALG: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512BW: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512CD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512F: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512FP16: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512IFMA: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI2: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512VL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVX512VPOPCNTDQ: 'true'
    feature.node.kubernetes.io/cpu-cpuid.AVXVNNI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.BHI_CTRL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CETIBT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CETSS: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CLDEMOTE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CMPSB_SCADBS_SHORT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8: 'true'
    feature.node.kubernetes.io/cpu-cpuid.ENQCMD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FLUSH_L1D: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FMA3: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FSRM: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FXSR: 'true'
    feature.node.kubernetes.io/cpu-cpuid.FXSROPT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.GFNI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IA32_ARCH_CAP: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IA32_CORE_CAP: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IBPB: 'true'
    feature.node.kubernetes.io/cpu-cpuid.IDPRED_CTRL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.LAHF: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MD_CLEAR: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVBE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVDIR64B: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVDIRI: 'true'
    feature.node.kubernetes.io/cpu-cpuid.MOVSB_ZL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.PCONFIG: 'true'
    feature.node.kubernetes.io/cpu-cpuid.PSFD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.RRSBA_CTRL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SERIALIZE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SHA: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.STIBP: 'true'
    feature.node.kubernetes.io/cpu-cpuid.STOSB_SHORT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SYSCALL: 'true'
    feature.node.kubernetes.io/cpu-cpuid.SYSEE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.TME: 'true'
    feature.node.kubernetes.io/cpu-cpuid.TSXLDTRK: 'true'
    feature.node.kubernetes.io/cpu-cpuid.VAES: 'true'
    feature.node.kubernetes.io/cpu-cpuid.VMX: 'true'
    feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ: 'true'
    feature.node.kubernetes.io/cpu-cpuid.WAITPKG: 'true'
    feature.node.kubernetes.io/cpu-cpuid.WBNOINVD: 'true'
    feature.node.kubernetes.io/cpu-cpuid.X87: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XGETBV1: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVE: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVEC: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT: 'true'
    feature.node.kubernetes.io/cpu-cpuid.XSAVES: 'true'
    feature.node.kubernetes.io/cpu-cstate.enabled: 'true'
    feature.node.kubernetes.io/cpu-hardware_multithreading: 'true'
    feature.node.kubernetes.io/cpu-model.family: '6'
    feature.node.kubernetes.io/cpu-model.id: '143'
    feature.node.kubernetes.io/cpu-model.vendor_id: Intel
    feature.node.kubernetes.io/cpu-pstate.scaling_governor: powersave
    feature.node.kubernetes.io/cpu-pstate.status: active
    feature.node.kubernetes.io/cpu-pstate.turbo: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTCMT: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTL2CA: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTL3CA: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTMBA: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTMBM: 'true'
    feature.node.kubernetes.io/cpu-rdt.RDTMON: 'true'
    feature.node.kubernetes.io/kernel-config.NO_HZ: 'true'
    feature.node.kubernetes.io/kernel-config.NO_HZ_FULL: 'true'
    feature.node.kubernetes.io/kernel-version.full: 6.8.0-45-generic
    feature.node.kubernetes.io/kernel-version.major: '6'
    feature.node.kubernetes.io/kernel-version.minor: '8'
    feature.node.kubernetes.io/kernel-version.revision: '0'
    feature.node.kubernetes.io/pci-0300_1a03.present: 'true'
    feature.node.kubernetes.io/pci-1200_1ed2.present: 'true'
    feature.node.kubernetes.io/pci-1200_1ed2.sriov.capable: 'true'
    feature.node.kubernetes.io/storage-nonrotationaldisk: 'true'
    feature.node.kubernetes.io/system-os_release.ID: ubuntu
    feature.node.kubernetes.io/system-os_release.VERSION_ID: '22.04'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: '22'
    feature.node.kubernetes.io/system-os_release.VERSION_ID.minor: '04'
    furiosa.ai/driver.version: 1.0.12
    furiosa.ai/driver.version.major: '1'
    furiosa.ai/driver.version.metadata: 5c48a42
    furiosa.ai/driver.version.minor: '0'
    furiosa.ai/driver.version.patch: '12'
    furiosa.ai/npu.count: '2'
    furiosa.ai/npu.family: rngd
    furiosa.ai/npu.product: rngd
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ms03-ceo-008
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ''
    node.kubernetes.io/exclude-from-external-load-balancers: ''
```
